
package webservices;

import java.io.FileInputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PaqueteWebServiceService", targetNamespace = "http://WebServices/")
public class PaqueteWebServiceService extends Service {

    private static URL PAQUETEWEBSERVICESERVICE_WSDL_LOCATION;
    private static WebServiceException PAQUETEWEBSERVICESERVICE_EXCEPTION;
    private static final QName PAQUETEWEBSERVICESERVICE_QNAME = new QName("http://WebServices/", "PaqueteWebServiceService");

    static {
        Properties prop = new Properties();
        String propFilePath = "/ens/home01/j/joaquin.campo/Descargas/config.properties"; // Ruta al archivo de propiedades
        try (FileInputStream input = new FileInputStream(propFilePath)) {
            // Carga el archivo de propiedades
            prop.load(input);
            // Lee la propiedad wsdlLocation para el servicio Paquete
            String wsdlLocation = prop.getProperty("paqueteWsdlLocation", "http://localhost:8086/PaqueteWebService?wsdl");
            PAQUETEWEBSERVICESERVICE_WSDL_LOCATION = new URL(wsdlLocation);
        } catch (IOException e) {
            PAQUETEWEBSERVICESERVICE_EXCEPTION = new WebServiceException("No se pudo leer la ubicación del WSDL del servicio Paquete.", e);
        }
    }


    public PaqueteWebServiceService() {
        super(__getWsdlLocation(), PAQUETEWEBSERVICESERVICE_QNAME);
    }

    public PaqueteWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAQUETEWEBSERVICESERVICE_QNAME, features);
    }

    public PaqueteWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, PAQUETEWEBSERVICESERVICE_QNAME);
    }

    public PaqueteWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAQUETEWEBSERVICESERVICE_QNAME, features);
    }

    public PaqueteWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaqueteWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaqueteWebService
     */
    @WebEndpoint(name = "PaqueteWebServicePort")
    public PaqueteWebService getPaqueteWebServicePort() {
        return super.getPort(new QName("http://WebServices/", "PaqueteWebServicePort"), PaqueteWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaqueteWebService
     */
    @WebEndpoint(name = "PaqueteWebServicePort")
    public PaqueteWebService getPaqueteWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices/", "PaqueteWebServicePort"), PaqueteWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAQUETEWEBSERVICESERVICE_EXCEPTION!= null) {
            throw PAQUETEWEBSERVICESERVICE_EXCEPTION;
        }
        return PAQUETEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
