
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "OfertaNoValidaParaEsaFecha", targetNamespace = "http://WebServices/")
public class OfertaNoValidaParaEsaFecha_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OfertaNoValidaParaEsaFecha faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public OfertaNoValidaParaEsaFecha_Exception(String message, OfertaNoValidaParaEsaFecha faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public OfertaNoValidaParaEsaFecha_Exception(String message, OfertaNoValidaParaEsaFecha faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.OfertaNoValidaParaEsaFecha
     */
    public OfertaNoValidaParaEsaFecha getFaultInfo() {
        return faultInfo;
    }

}
