
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "TipoOfertaExiste", targetNamespace = "http://WebServices/")
public class TipoOfertaExiste_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TipoOfertaExiste faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TipoOfertaExiste_Exception(String message, TipoOfertaExiste faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public TipoOfertaExiste_Exception(String message, TipoOfertaExiste faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.TipoOfertaExiste
     */
    public TipoOfertaExiste getFaultInfo() {
        return faultInfo;
    }

}
