
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "TipoOfertaNoExiste", targetNamespace = "http://WebServices/")
public class TipoOfertaNoExiste_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TipoOfertaNoExiste faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TipoOfertaNoExiste_Exception(String message, TipoOfertaNoExiste faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public TipoOfertaNoExiste_Exception(String message, TipoOfertaNoExiste faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.TipoOfertaNoExiste
     */
    public TipoOfertaNoExiste getFaultInfo() {
        return faultInfo;
    }

}
