
package webservices;

import java.io.FileInputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UsuarioWebServiceService", targetNamespace = "http://WebServices/")
public class UsuarioWebServiceService extends Service {

    private static URL USUARIOWEBSERVICESERVICE_WSDL_LOCATION;
    private static WebServiceException USUARIOWEBSERVICESERVICE_EXCEPTION;
    private static final QName USUARIOWEBSERVICESERVICE_QNAME = new QName("http://WebServices/", "UsuarioWebServiceService");

    static {
        Properties prop = new Properties();
        String propFilePath = "/ens/home01/j/joaquin.campo/Descargas/config.properties"; // Ruta al archivo de propiedades
        try (FileInputStream input = new FileInputStream(propFilePath)) {
            // Carga el archivo de propiedades
            prop.load(input);
            // Lee la propiedad wsdlLocation para el servicio Usuario
            String wsdlLocation = prop.getProperty("usuarioWsdlLocation", "http://localhost:8081/UsuarioWebService?wsdl");
            USUARIOWEBSERVICESERVICE_WSDL_LOCATION = new URL(wsdlLocation);
        } catch (IOException e) {
            USUARIOWEBSERVICESERVICE_EXCEPTION = new WebServiceException("No se pudo leer la ubicación del WSDL del servicio Usuario.", e);
        }
    }


    public UsuarioWebServiceService() {
        super(__getWsdlLocation(), USUARIOWEBSERVICESERVICE_QNAME);
    }

    public UsuarioWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOWEBSERVICESERVICE_QNAME, features);
    }

    public UsuarioWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOWEBSERVICESERVICE_QNAME);
    }

    public UsuarioWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOWEBSERVICESERVICE_QNAME, features);
    }

    public UsuarioWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsuarioWebService
     */
    @WebEndpoint(name = "UsuarioWebServicePort")
    public UsuarioWebService getUsuarioWebServicePort() {
        return super.getPort(new QName("http://WebServices/", "UsuarioWebServicePort"), UsuarioWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioWebService
     */
    @WebEndpoint(name = "UsuarioWebServicePort")
    public UsuarioWebService getUsuarioWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices/", "UsuarioWebServicePort"), UsuarioWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOWEBSERVICESERVICE_EXCEPTION!= null) {
            throw USUARIOWEBSERVICESERVICE_EXCEPTION;
        }
        return USUARIOWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
