
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "UsuarioNickExiste", targetNamespace = "http://WebServices/")
public class UsuarioNickExiste_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioNickExiste faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioNickExiste_Exception(String message, UsuarioNickExiste faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public UsuarioNickExiste_Exception(String message, UsuarioNickExiste faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.UsuarioNickExiste
     */
    public UsuarioNickExiste getFaultInfo() {
        return faultInfo;
    }

}
